<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // An audit trail of every payment attempt, successful or not. This is
        // the source of truth we reconcile against Paystack's dashboard with,
        // and it's what the webhook writes to when Paystack confirms a charge.
        Schema::create('payments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();

            // Paystack's unique reference for this transaction attempt.
            // Generated by us before redirecting to Paystack, so we can match
            // the webhook callback back to this row.
            $table->string('reference')->unique();

            $table->string('plan');
            $table->unsignedInteger('amount_pesewas'); // store in the smallest currency unit
            $table->string('currency')->default('GHS');

            // pending -> initialized but not yet confirmed by Paystack
            // success  -> webhook confirmed payment
            // failed   -> webhook/verify reported failure
            // abandoned -> user never completed checkout
            $table->string('status')->default('pending');

            $table->string('paystack_transaction_id')->nullable();
            $table->json('gateway_response')->nullable(); // raw payload for debugging/audit

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('payments');
    }
};
